### PR TITLE
Misc modifications

### LINKED ISSUE #11: Enable "auto-verify" when generating the public key
# Objective
In order to complete the NEAR Ledger Live integration, we need a way to "get the public key" without requiring user interaction. 

# Issue
The docs in this repo seem to be incorrect - the `GET ADDRESS` section of [the docs](https://github.com/LedgerHQ/app-near/blob/master/workdir/app-near/doc/api.asc) mentions that we can use the `P1` to either just return the address, or display and then return the address. However, it looks like the `p1` is marked as unused here: https://github.com/LedgerHQ/app-near/blob/master/workdir/app-near/src/get_public_key.c#L47

This should instead be used to determine whether or not to display something to the user before returning the public key.

# Additional Notes
Some other Nano apps have this functionality, and might be used for reference, for example the Celo app: https://github.com/LedgerHQ/app-celo-spender/blob/master/src/main.c#L182

### PR DESCRIPTION
**Pull request by sgliner-ledger**
- Make use of P1 field in GET_PUBLIC_KEY (0x04) instruction to enable silent export of public key (fixes #11)
- Add new GET_WALLET_ID (0x05) instruction to enable display and verification of regular wallet id

### CODE REVIEW

File: workdir/app-near/src/get_public_key.h [hunk 1]
```diff
@@ -5,6 +5,11 @@
 #ifndef _GET_PUBLIC_KEY_H_
 #define _GET_PUBLIC_KEY_H_
 
+enum p1_values_e {
+    RETURN_ONLY,
```
Comment (xchapron-ledger) [inline workdir/app-near/src/get_public_key.h]: Maybe `RETURN_ONLY = 0,` to be more explicit? Same for `DISPLAY_AND_CONFIRM`? What do you think?

File: workdir/app-near/src/get_wallet_id.c [hunk 2]
```diff
@@ -0,0 +1,77 @@
...
+    {
+        THROW(INVALID_PARAMETER);
+    }
+
+    memcpy(tmp_ctx.address_context.public_key, public_key.W, 32);
+
+    memset(wallet_id, '0', sizeof(wallet_id));
+
+    for (uint8_t i = 0; i < 32; i++) {
+        snprintf(&wallet_id[2*i], 4, "%02x", public_key.W[i]);
```
Comment (xchapron-ledger) [inline workdir/app-near/src/get_wallet_id.c]: why 4?
This loop could be replaced by something like:
`snprintf(wallet_id, sizeof(wallet_id), "%.*H", 32, public_key.W);`

File: workdir/app-near/src/get_wallet_id.c [hunk 3]
```diff
@@ -0,0 +1,77 @@
+#include "get_wallet_id.h"
+#include "os.h"
+#include "ux.h"
+#include "utils.h"
+#include "main.h"
+
+static char wallet_id[65];
```
Comment (xchapron-ledger) [inline workdir/app-near/src/get_wallet_id.c:7]: Does this app as shortage of RAM or not?
If so we might want to optimize this?

File: workdir/app-near/tests/conftest.py [hunk 4]
```diff
@@ -0,0 +1,75 @@
...
+        "--display", "headless"
+    ]
+
+    # Look for the automation_file attribute in the test function, if present
+    try:
+        automation_args = ["--automation", f"file:{request.function.automation_file}"]
+    except AttributeError:
+        automation_args = []
+
+    speculos_proc = subprocess.Popen([*base_args, *automation_args])
```
Comment (xchapron-ledger) [inline workdir/app-near/tests/conftest.py:45]: Might be replaced by something like:

```
from speculos.client import SpeculosClient

speculos_client = SpeculosClient(app="./NEAR-bin/app.elf", args=["--sdk", "2.0", "--display", "headless", *automation_args])
speculos_client.start()
```

File: workdir/app-near/tests/test_get_key.py [hunk 5]
```diff
@@ -0,0 +1,28 @@
+from hashlib import sha256
+import json
+from pathlib import Path
+from typing import Tuple, List, Dict, Any
+import pytest
+
+from utils import automation
+
+def test_get_public_key_no_confirm(transport):
+    apdu = "80040057148000002c8000018d800000008000000080000001"
```
Comment (xchapron-ledger) [inline workdir/app-near/tests/test_get_key.py]: Speculos API might be used to construct the APDU instead of having its raw hex displayed here?

**Review by rgeslain-ledger — APPROVED** [review]

File: workdir/app-near/tests/test_get_key.py [hunk 6]
```diff
@@ -0,0 +1,28 @@
...
+    sw, key = transport.exchange_raw(apdu)
+    assert sw == 0x9000
+    assert key.hex() == "c4f5941e81e071c2fd1dae2e71fd3d859d462484391d9a90bf219211dcbb320f"
```
Comment (xchapron-ledger) [inline workdir/app-near/tests/test_get_key.py]: Maybe a kind of define explaining that this is the NEAR address corresponding to speculos default seed?

File: workdir/app-near/src/get_wallet_id.c [hunk 7]
```diff
@@ -0,0 +1,75 @@
...
+    if (!get_ed25519_public_key_for_path(path, &public_key))
+    {
+        THROW(INVALID_PARAMETER);
+    }
+
+    memcpy(tmp_ctx.address_context.public_key, public_key.W, 32);
+
+    memset(wallet_id, '0', sizeof(wallet_id));
+
+    snprintf(&wallet_id, sizeof(wallet_id), "%.H", 32, public_key.W);
```
Comment (xchapron-ledger) [inline workdir/app-near/src/get_wallet_id.c]: Does the memset does anything? Is is intended that it fills with `'0'` and not `0` or `'\0'`
I think that the worst case would be a wallet_id buffer that is too short to fit the key, which would ends with no `\0` after the `snprintf`. But this can't arrive as 65 = 32 * 2 + 1, and the memset before the snprintf would not help anyway...

File: workdir/app-near/src/get_public_key.h (hunk 1 above)
Comment (sgliner-ledger) [reply workdir/app-near/src/get_public_key.h]: Done :)

File: workdir/app-near/src/get_wallet_id.c (hunk 3 above)
Comment (sgliner-ledger) [reply workdir/app-near/src/get_wallet_id.c:7]: No shortage :)

File: workdir/app-near/src/get_wallet_id.c (hunk 7 above)
Comment (sgliner-ledger) [reply workdir/app-near/src/get_wallet_id.c]: You're right thanks :)

**Review by xchapron-ledger — APPROVED** [review]
